### ISSUE TITLE
Class level annotations

### ISSUE THREAD

**Issue by alexseguin** [AES-Outreach/SwaggerGen#54]
Need to implement support for class level annotations within the PathGenerator. This would help lighten the method annotations by extracting common annotations from the classes.

With this change, it could also be possible to turn the endpoint method property within the annotations into a method level annotations to further lighten the annotation writing process.

**Comment by Billzzhang** [comment]
Make scheme class level

**Comment by Billzzhang** [comment]
Class level headers that add onto method level headers
