### ISSUE TITLE
Publish to public maven repository

### ISSUE THREAD

**Issue by alexseguin** [AES-Outreach/SwaggerGen#70]
https://issues.sonatype.org/browse/OSSRH-48919

**Comment by alexseguin** [comment]
awaiting status update before running mvn deploy on the project.

**Comment by GuillaumeC91** [comment]
Relates to #68 as indicated in https://issues.sonatype.org/browse/OSSRH-48919

**Comment by alexseguin** [comment]
I already made the change to #68, Travis is failing on some other issue I'll investigate after work

**Comment by pat-lego** [comment]
Make the swaggergen plugin open in Nexus
